#!/system/bin/sh

# rild test stuff

case $1 in
    ppp1)
        echo 0 > /proc/sys/net/ipv4/ip_forward;
        ;;
esac

/system/bin/setprop "net.$LINKNAME.dns1" ""
/system/bin/setprop "net.$LINKNAME.dns2" "" 
/system/bin/setprop "net.$LINKNAME.local-ip" "" 
/system/bin/setprop "net.$LINKNAME.remote-ip" "" 
/system/bin/setprop "net.$LINKNAME.gw" ""
/system/bin/setprop "net.$LINKNAME.if" ""
